### PR TITLE
navbar and header changes

### PR DESCRIPTION
**Pull request by reveurguy**
Signed-off-by: Priyanshu Singh <reveur.guy99@gmail.com>

## Description
Made initial changes to header. Added background to navbar and header sections.

In reference to #158 

## Test

To test this pull request, you can run the following commands:

### CODE REVIEW

**Comment by reveurguy** [comment]
You can see the changes on this link:
https://capable-lokum-3c4090.netlify.app/

**Comment by divya-mohan0209** [comment]
@reveurguy : Thank you for your changes but these are brand templates that didn't need modification unless they have been explicitly conveyed by the Kubewarden team. Please may I know if you've received any such communication?

**Comment by divya-mohan0209** [comment]
cc: @flavio

**Comment by reveurguy** [comment]
Hi @divya-mohan0209 No i didn't receive any communication for the changes and did them on my own. I kept the color scheme same just added some background. I'll undo the background related changes if that's an issue.

**Comment by divya-mohan0209** [comment]
Please undo the changes since they're specified by our brands/marketing team.

**Pull request closed without merging**
