### PR TITLE
New architecture

### PR DESCRIPTION
**Pull request by raulcabello**
fixes  kubewarden/kubewarden.io#27

### CODE REVIEW

**Review by flavio — APPROVED** [review]
LGTM, of course we will merge it only once all the work on the new-architecture is done

**Comment by raulcabello** [comment]
I think we can merge into the new-architecture branch, then merge into main once the rest of new-architecture code is merged

**Comment by ereslibre** [comment]
@raulcabello commits can be squashed. Not blocking, but I think would be nice to do before merging.

**Comment by raulcabello** [comment]
@ereslibre sure! I can squash before merging. @flavio are you ok with merging this into the new-architecture branch?

**Review by flavio — APPROVED** [review]
I'm totally fine with this PR. Squash the commits as @ereslibre suggested

**Pull request merged**
