### PR TITLE
Update Admission Policy blogpost

### PR DESCRIPTION
**Pull request by divya-mohan0209**
Fixed a few grammatical nits and modified a few sentences for clarity.

### CODE REVIEW

**Review by raulcabello — APPROVED** [review]
changes look good to me, but we already published the blog last week

**Comment by divya-mohan0209** [comment]
Thanks @raulcabello ! Do we not have a last edited feature/mention on the current documentation tool anywhere so that we can edit for any grammatical/spelling nits?

**Review by jvanz — APPROVED** [review]

**Comment by jvanz** [comment]
> Thanks @raulcabello ! Do we not have a last edited feature/mention on the current documentation tool anywhere so that we can edit for any grammatical/spelling nits?

AFAIK, we do not have this feature. However, I think we should merge the fixes anyway.

**Review by ereslibre — APPROVED** [review]
LGTM, although published. We can add a "last modified" date as part of the blog post metadata.

**Comment by flavio** [comment]
I've fixed the build issue caused by the hugo update, plus I changed the template we have to show a "last update" attribute

image

**Pull request merged**
