### PR TITLE
New blog post about 1.16.1 releases

### PR DESCRIPTION
**Pull request by flavio**
Cover the patch releases of policy server and kwctl

### CODE REVIEW

**Comment by flavio** [comment]
@jhkrug can you take a quick look at that please?

**Review by jvanz — APPROVED** [review]

**Comment by jhkrug** [comment]
Ok, sorry, I missed that. I've just come out of a long meeting. I shall take a look now.

**Comment by jhkrug** [comment]
And it looks fine.

**Comment by flavio** [comment]
No worries, thanks!

**Pull request merged**
