### PR TITLE
Simple news ticker added

### PR DESCRIPTION
**Pull request by kkaempf**
This is a simple, table-based news ticker. Maybe Hugo has better means, but I was not able to find them.

Signed-off-by: Klaus Kämpf <kkaempf@suse.de>

### CODE REVIEW

**Comment by kkaempf** [comment]
This is how it looks:

kubewarden-news-ticker

**Comment by flavio** [comment]
I'll be honest, I don't like it. It doesn't integrate well into the header. I think we should just a add a new "News/Blog" section (like we do with hub, chart,...).

With hugo you can have static contents and blog entries. As soon as we start adding blog entries, these will show up under the "/blog" section.

**Comment by ereslibre** [comment]
I wonder if we could use a regular hugo blog under `/blog`, with RSS generation enabled. The frontend of `kubewarden.io` could perform a client request to this RSS and render that widget. Maybe it's overkill though, but it would ensure it's always up to date and in sync with the blog contents.

**Comment by flavio** [comment]
Closing, as discussed during the daily we would prefer to go ahead with this solution:

* Extend the current hugo website to have also `blog` contents
* Publish all the blog entries under the `https://kubewarden.io/blog`
* Have a sidebar with the most recent blog posts. This can be generated when building the website

**Pull request closed without merging**
