### PR TITLE
Add aarch64 blog post

### PR DESCRIPTION
**Pull request by ereslibre**
Fixes: https://github.com/kubewarden/kubewarden.io/issues/46

### CODE REVIEW

**Review by viccuad — APPROVED** [review]

**Review by jvanz — APPROVED** [review]

**Comment by kkaempf** [comment]
:+1:

**Review by flavio — APPROVED** [review]
LGTM

**Comment by flavio** [comment]
Let's publish that on Monday.

CC @robertsirc: I don't think this is something that deserves other kind of promotions

**Comment by robertsirc** [comment]
I will look at this today. We can get a tweet or two out on this.

**Comment by ereslibre** [comment]
Merging as mentioned in slack.

**Pull request merged**
