### PR TITLE
Addressing grammatical nits in writing-your-first-policy-with-kubewarden.md

### PR DESCRIPTION
**Pull request by prrajput1199**
## Description
Addressing grammatical nits in writing-your-first-policy-with-kubewarden.md

### CODE REVIEW

**Review by flavio — APPROVED** [review]
Thanks a lot for these fixes!

**Comment by flavio** [comment]
@prrajput1199 can you please fix the DCO check please? You can see how to fix it [here](https://github.com/kubewarden/kubewarden.io/pull/171/checks?check_run_id=11172332809)

**Comment by prrajput1199** [comment]
@flavio I fixed the DCO check. Can you check please?.

**Comment by flavio** [comment]
All good, thanks again

**Pull request merged**
