### PR TITLE
feat: Add more subtle code scss for 1-line code blocks

### PR DESCRIPTION
**Pull request by viccuad**
## Description

Before:

code_before

After:

code

## Test

See the render.

### CODE REVIEW

**Review by jhkrug — COMMENTED** [review]
Screenshot_2024-04-24_15-21-40

I think that `font-size: 100%;` will look better. Probably, or something close to 100%. That original is too big. I think 15px is a bit small though. To me, looks weird.

**Comment by viccuad** [comment]
I'm happy with whatever, to me the current style is a bit unreadable. I tried just with the same style as for multiline code blocks, and it's too in-your-face:

**Comment by flavio** [comment]
I would go ahead and make the change suggested by @jhkrug. I don't like the screenshot with the black background

**Comment by viccuad** [comment]
Rebased with `font-size: 90%`

image

**Comment by jvanz** [comment]
> I would go ahead and make the change suggested by @jhkrug. I don't like the screenshot with the black background

Same to me

**Comment by viccuad** [comment]
merging with 0.9 then.

**Pull request merged**
