### PR TITLE
Fix mobile menu - update theme submodule

### PR DESCRIPTION
**Pull request by jordojordo**
## Description
This fixes the issue with the mobile navigation not being styled correctly. The issue was a combination of the submodule not being updated and the custom header partial and main.scss missing the `.menu-toggle` styling. 

Fix https://github.com/rancherlabs/projects-theme/issues/4 && #30 

## Test

To test this pull request, you can run the following commands:
- Run the server with `hugo server -D`
- Open the responsive design mode in the browser (ctrl + shift + m - on firefox)

## Additional Information

https://user-images.githubusercontent.com/40806497/163265340-0e9ee00e-b5d5-4ece-a58c-3f90629be1c7.mp4

### CODE REVIEW

**Review by jvanz — APPROVED** [review]
LGTM! :D

**Comment by jvanz** [comment]
Just a question which is **not** a blocker to merge this PR for me... I notice that menu button is on the right and the menu is opened  in the left. Is difficult to make the menu open in the same side of the button? :grimacing:

**Review by viccuad — APPROVED** [review]
LGTM! Many thanks! :D

**Comment by jordojordo** [comment]
@jvanz It wouldn't be too difficult to move the whole container to the right side. With the merge to Docusaurus do you think it would be worth to update that as well?

**Review by divya-mohan0209 — APPROVED** [review]
lgtm from me! Thank you so much @jordojordo

**Comment by jvanz** [comment]
> @jvanz It wouldn't be too difficult to move the whole container to the right side. With the merge to Docusaurus do you think it would be worth to update that as well?

Oh, yeah! You are right. Merging now! Thanks again!

**Pull request merged**
