### PR TITLE
Remove values flag from failing updatecli call

### PR DESCRIPTION
**Pull request by jhkrug**
## Description

updatecli for updating the version number on the landing page has been failing. Updatecli no longer supports a --values flag.

### CODE REVIEW

**Comment by jhkrug** [comment]
I think that should work. I can only partialy test it. I can see that a correct change is constructed but an end-to-end test is eluding me.

**Comment by flavio** [comment]
@olblak can you take a look at that please? :pray:

**Comment by jhkrug** [comment]
Ok, testing worked with a classic token for GITHUB_TOKEN. 

All works fine now, just it's not DCO signed. Which can be overidden in the PR. Can updatecli do a correct DCO?

**Comment by olblak** [comment]
If the commit is created using the GITHUB_TOKEN then commit are signed similar to https://github.com/updatecli/updatecli/commit/5a354f5911ff0cd7ed6dce3c3df2ff0decd0c457

Assuming it's still needed, the values file must be configured in [updatecli-compose.yaml](https://github.com/kubewarden/kubewarden.io/blob/main/updatecli-compose.yaml) if you need to use the command `updatecli compose diff`

Something like 

```
policies:
  - name: Kubewarden specific policies
    config: 
      - updatecli/updatecli.d/
    values:
      - updatecli/values.yml
```

**Comment by olblak** [comment]
The values file doesn't seem to be used so I think it can be delete

**Comment by olblak** [comment]
Just tested this manifest, are you happy with
https://github.com/olblak/kubewarden.io/pull/1/commits/8621c0dbf127855e6f9e256448b8a7bc635eef9c 
?

**Comment by olblak** [comment]
Keep in mind that this commit is not signed by GitHub action because I run updatecli from my machine

**Comment by olblak** [comment]
Mmmmh I see that the commit are pushed by "Chimera-kube-bot"

https://github.com/kubewarden/kubewarden.io/commits?author=chimera-kube-bot

**Comment by olblak** [comment]
@jhkrug I created https://github.com/jhkrug/kubewarden.io/pull/4 which contains a few cleanup
Also I tested it on my fork to create https://github.com/olblak/kubewarden.io/pull/3/commits/9084f2212e5d9f672bd598177c1eed432673721c

**Comment by olblak** [comment]
Tested to create this commit https://github.com/olblak/kubewarden.io/pull/3/commits/9084f2212e5d9f672bd598177c1eed432673721c

**Pull request merged**
